variables:
  IMAGE_NAME: ktcode/garden-app-gitlab
  IMAGE_TAG: garden-app-gitlab-1.0


stages:
  - test
  - build
  - deploy

run_tests:
  before_script:
    - echo "starting test stage"
  script:
    - echo "test stage"

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "starting build stage"
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

